### PR TITLE
Add test specification for KDF/PFKDF.

### PR DESCRIPTION
**Pull request by sighingnow**
+ Add test/Z/Crypto/KDFSpec.hs.
+ Re-indent some test files as we use 4-space indentation in this repo.

### CODE REVIEW

**Comment by sighingnow** [comment]
The test is not enabled on Linux and Mac, but locally validation on Windows works fine.

**Comment by winterland1989** [comment]
> The test is not enabled on Linux and Mac, but locally validation on Windows works fine.

Let’s enable them then! Mingw has some strange problem, let’s ignore it for now.

**Comment by sighingnow** [comment]
> > The test is not enabled on Linux and Mac, but locally validation on Windows works fine.
> 
> Let’s enable them then! Mingw has some strange problem, let’s ignore it for now.

Will fixes that later :)

**Comment by winterland1989** [comment]
Thanks!

**Pull request merged**
